models.py
from _init_ import *
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))

main.py
from _init_ import create_app


app = create_app()

if __name__ == '__main__':
    app.run(debug=True)

views.py
from flask import Blueprint, render_template, Response, send_file, redirect, url_for, request, Flask, flash
from flask_login import login_required, current_user
import glob
import os
from gaze_tracker import GazeTracker
from werkzeug.utils import secure_filename
GazeTracker = GazeTracker()
class ApplicationWindows:

    views = Blueprint('views', __name__)

    ALLOWED_EXTENSIONS = {'csv', 'mp4'}

    @views.route('/')
    def home(self):
        return render_template("home.html", user=current_user)


    @views.route('/gaze-real', methods=['GET', 'POST'])
    def gaze_real(self):
        return render_template("gaze_real.html", user=current_user)


    @views.route('/download')
    def download_file(self):
        list_of_files = glob.glob('*.csv')  # * means all if need specific format then *.csv
        latest_file = max(list_of_files, key=os.path.getctime)
        p = latest_file
        return send_file(p, as_attachment=True)


    def allowed_file(filename):
        return '.' in filename and \
               filename.rsplit('.', 1)[1].lower() in ApplicationWindows.ALLOWED_EXTENSIONS


    def gen_frames_algorithm(self):  # generate frame by frame from camera
        time_right = 0
        time_center = 0
        time_left = 0
        while True:
            success, frame = GazeTracker.camera.read()
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            faces = GazeTracker.detector(gray)
            for face in faces:
                x, y = face.left(), face.top()
                x1, y1 = face.right(), face.bottom()
                cv2.rectangle(frame, (x, y), (x1, y1), (0, 255, 0), 1)
                landmarks = GazeTracker.predictor(gray, face)
                gaze_ratio_left_eye = GazeTracker.get_gaze_ratio(frame, gray, [36, 37, 38, 39, 40, 41], landmarks)
                gaze_ratio_right_eye = GazeTracker.get_gaze_ratio(frame, gray, [42, 43, 44, 45, 46, 47], landmarks)
                gaze_ratio = (gaze_ratio_right_eye + gaze_ratio_left_eye) / 2
                new_frame = np.zeros((500, 500, 3), np.uint8)
                start = time.time()
                print(gaze_ratio)
                if GazeTracker.gaze_ratio >= GazeTracker.gaze_right:
                    cv2.putText(frame, "LEFT", (x - 100, y), GazeTracker.font, 1, (0, 0, 255), 2)
                    new_frame[:] = (0, 0, 255)
                    end1 = time.time()
                    time_left += (end1 - start) * 100
                elif GazeTracker.gaze_right > gaze_ratio > GazeTracker.gaze_left:
                    cv2.putText(frame, "CENTER", (x - 100, y), font, 1, (0, 0, 255), 2)
                    end2 = time.time()
                    time_center += (end2 - start) * 1000
                else:
                    new_frame[:] = (255, 0, 0)
                    cv2.putText(frame, "RIGHT", (x - 100, y), font, 1, (0, 0, 255), 2)
                    end3 = time.time()
                    time_right += (end3 - start) * 100
                now = datetime.now()
                d3 = dt_string = now.strftime("%d_%m_%Y_%H_%M_%S")
                with open(d3 + '.csv', 'w', newline='') as f:
                    thewriter = csv.writer(f)
                    thewriter.writerow(['Gaze direction:', 'Time (s):'])
                    thewriter.writerow(['Left', time_left])
                    thewriter.writerow(['Right', time_right])
                    thewriter.writerow(['Center', time_center])
                ret, buffer = cv2.imencode('.jpg', frame)
                frame = buffer.tobytes()
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


    def gen_frames(self):
        while True:
            success, frame = GazeTracker.camera.read()
            if not success:
                break
            else:
                ret, buffer = cv2.imencode('.jpg', frame)
                frame = buffer.tobytes()
                yield (b'--frame\r\n'
                       b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n')


    @views.route('/video_feed_base')
    def video_feed_base(self):
        return Response(ApplicationWindows.gen_frames(), mimetype='multipart/x-mixed-replace; boundary=frame')


    @views.route('/video_feed')
    def video_feed(self):
        return Response(ApplicationWindows.gen_frames_algorithm(), mimetype='multipart/x-mixed-replace; boundary=frame')


    @views.route("/gaze-analyse", methods=["GET", "POST"])
    def gaze_analyse(self):
        if request.method == 'POST':
            if 'file' not in request.files:
                flash('No file part')
                return redirect(request.url)
            file = request.files['file']
            if file.filename == '':
                flash('No selected file')
                return redirect(request.url)
            if not ApplicationWindows.allowed_file(file.filename):
                flash('Wrong file format', "error")
                return redirect(request.url)
            if file and ApplicationWindows.allowed_file(file.filename):
                filename = secure_filename(file.filename)
                if filename.endswith('.mp4'):
                    result = GazeTracker.analyse_video(os.path.abspath(filename))
                    print(result)
                    if result == 'Low':
                        flash('Student cheating risk: ' + result)
                    else:
                        flash('Student cheating risk: ' + result, "error")
                elif filename.endswith('.csv'):
                    if ApplicationWindows.analyse_csv(os.path.abspath(filename)) == 'Low':
                        flash('Student cheating risk: ' + ApplicationWindows.analyse_csv(os.path.abspath(filename)))
                    else:
                        flash('Student cheating risk: ' + ApplicationWindows.analyse_csv(os.path.abspath(filename)), "error")
        return render_template("gaze_analyse.html", user=current_user)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="gaze_real" href="/gaze-real">Real Gaze</a>
          <a class="nav-item nav-link" id="gaze_analyze" href="/gaze-analyse">Gaze Analyse</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signup" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

    <script
      type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}"
    ></script>
  </body>
</html>

templates/gaze_analyse.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">

      <h1>Analyse students cheating risk with a file (.csv or .mp4 format)</h1>
      <hr>

      <form action="/gaze-analyse" method="POST" enctype="multipart/form-data">

        <div class="form-group">
          <label>Select a file</label>
          <div class="custom-file">
            <input type="file" class="custom-file-input" name="file" id="file">
            <label class="custom-file-label" for="file">Select a file...</label>
          </div>
        </div>

        <button type="submit" class="btn btn-primary">Analyse</button>

      </form>

    </div>
  </div>
</div>

{% endblock %}

templates/gaze_real.html
{% extends "base.html" %} {% block title %}Home{% endblock %}

{% block content %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Real time gaze detection</title>
    <script type="text/javascript">
        function change(){
            view1.src = "{{ url_for('views.video_feed') }}"
        }
        function change1(){
            view1.src = "{{ url_for('views.video_feed_base') }}"
        }


    </script>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-8  offset-lg-2">
            <h3 class="mt-5">Real time gaze detection</h3>
            <img src="{{ url_for('views.video_feed_base') }}" id="view1" width="100%">
        </div>
    </div>
</div>
<div class="col-lg-8  offset-lg-2">
<button onclick="change()" type="submit" class="btn btn-primary" id="1but">Start detection</button>
<button onclick="change1()" type="submit" class="btn btn-primary" id="2but">Stop detection</button>
    <a href="{{url_for('views.download_file')}}">Export data</a>
</div>
</body>
</html>
{% endblock %}

templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %}
{% block content %}
<html>
<body>

<div class="container">
    <div class="row">
        <div class="col-lg-8  offset-lg-2">
            <h3 class="mt-5">Gaze tracking system</h3>
            <p>This system is created to track eye position and register the data.</p>
            <p>Received data can be analysed, currently implemented to evaluate if a student is cheating.</p>
            <h3 class="mt-5">Must register and login to use</h3>
        </div>
    </div>
</div>


</body>
</html>

{% endblock %}

templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
  <h3 align="center">Login</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="password">Password</label>
    <input
      type="password"
      class="form-control"
      id="password"
      name="password"
      placeholder="Enter password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

templates/signup.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
content %}
<form method="POST">
  <h3 align="center">Sign Up</h3>
  <div class="form-group">
    <label for="email">Email Address</label>
    <input
      type="email"
      class="form-control"
      id="email"
      name="email"
      placeholder="Enter email"
    />
  </div>
  <div class="form-group">
    <label for="firstName">First Name</label>
    <input
      type="text"
      class="form-control"
      id="firstName"
      name="firstName"
      placeholder="Enter first name"
    />
  </div>
  <div class="form-group">
    <label for="password1">Password</label>
    <input
      type="password"
      class="form-control"
      id="password1"
      name="password1"
      placeholder="Enter password"
    />
  </div>
  <div class="form-group">
    <label for="password2">Password (Confirm)</label>
    <input
      type="password"
      class="form-control"
      id="password2"
      name="password2"
      placeholder="Confirm password"
    />
  </div>
  <br />
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}